## Task 12
- Create arrays with all the data types available in numpy
#### Data Types
- Integer - i
- Boolean - b
- Unsigned integer - u
- Float - f
- Complex float - c
- Timedelta - m
- Datatime - M
- Object - O
- String - S
- Unicode string - U

In [2]:
import numpy as np

In [3]:
a = np.array([79,80,81,82,83])   #integer
print(a)
a.dtype

[111 112 113 114 115]


dtype('int32')

In [4]:
a = np.array([79,80,81,82,83] ,dtype= 'bool')  #boolean
print(a)
a.dtype

[ True  True  True  True  True]


dtype('bool')

In [5]:
a = np.array([-79,-80,81,82,83] ,dtype= 'uint16') #unsigned integer 
print(a)
a.dtype

[65457 65456    81    82    83]


dtype('uint16')

In [6]:
a= np.array([12,442,33.33,7.8,9.67])   #float
print(a)
a.dtype

[ 12.   442.    33.33   7.8    9.67]


dtype('float64')

In [7]:
a = np.array([10.4,1 + 12j,90.38j])  #complex float
print(a)
a.dtype

[10.4 +0.j    1. +12.j    0. +90.38j]


dtype('complex128')

In [15]:
a=np.timedelta64(14, 'Y')   #timedelta
print(a)

14 years


In [16]:
a=np.timedelta64(14, 'M')   #timedelta
print(a)

14 months


In [14]:
a=np.array(['2019-04-12', '2014-04-09', '2011-06-12'], dtype='datetime64')   #datetime
a

array(['2019-04-12', '2014-04-09', '2011-06-12'], dtype='datetime64[D]')

In [11]:
a = np.array([27,56,98], dtype='O')  #object
a

array([27, 56, 98], dtype=object)

In [12]:
a = np.array(['Raghav', 'SRM', 'CSE_D'])  #String
print(a)
a.dtype

['Raghav' 'SRM' 'CSE_D']


dtype('<U6')

In [13]:
a = np.array([u'\u0065',u'\u2202r',u'\u1F601'], dtype='U')  #unicode string
a

array(['e', '∂r', 'ὠ1'], dtype='<U2')